services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: hirrao/health-server:latest
    container_name: health-server
    environment:
      - APP_USER
      - APP_PASSWORD
    volumes:
      - ./data:/data
    ports:
      - "8188:8188"
